// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: mykindlereader

#ifndef _MYKINDLEREADER_UI_H
#define _MYKINDLEREADER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_MainMenu.h"
#include "ui_BookSelection.h"
#include "ui_ReadingScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_output_png);    // assets/output.png
LV_IMG_DECLARE(ui_img_car_png);    // assets/car.png
LV_IMG_DECLARE(
    ui_img_battery_android_frame_full_20dp_000000_fill0_wght400_grad0_opsz20_png);    // assets/battery_android_frame_full_20dp_000000_FILL0_wght400_GRAD0_opsz20.png
LV_IMG_DECLARE(
    ui_img_battery_android_frame_full_20dp_ffffff_fill0_wght400_grad0_opsz20_png);    // assets/battery_android_frame_full_20dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png
LV_IMG_DECLARE(
    ui_img_heart_smile_20dp_ea3323_fill0_wght400_grad0_opsz20_png);    // assets/heart_smile_20dp_EA3323_FILL0_wght400_GRAD0_opsz20.png
LV_IMG_DECLARE(
    ui_img_book_17dp_ffffff_fill0_wght400_grad0_opsz20_png);    // assets/book_17dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png
LV_IMG_DECLARE(
    ui_img_nest_clock_farsight_analog_17dp_ffffff_fill0_wght400_grad0_opsz20_png);    // assets/nest_clock_farsight_analog_17dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_clockFont);
LV_FONT_DECLARE(ui_font_clockFont1);
LV_FONT_DECLARE(ui_font_bookTime);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
