// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: mykindlereader

#ifndef UI_BOOKSELECTION_H
#define UI_BOOKSELECTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BookSelection
extern void ui_BookSelection_screen_init(void);
extern void ui_BookSelection_screen_destroy(void);
extern lv_obj_t * ui_BookSelection;
extern lv_obj_t * ui_BookChoicePanel;
extern lv_obj_t * ui_TopBarPanel;
extern lv_obj_t * ui_Divider;
extern lv_obj_t * ui_Divider1;
extern lv_obj_t * ui_Divider2;
extern lv_obj_t * ui_BookName;
extern lv_obj_t * ui_PageNum;
extern lv_obj_t * ui_LastOpen;
extern lv_obj_t * ui_BookName1;
extern lv_obj_t * ui_PageNum1;
extern lv_obj_t * ui_LastOpen1;
extern lv_obj_t * ui_BookName2;
extern lv_obj_t * ui_PageNum2;
extern lv_obj_t * ui_LastOpen2;
extern lv_obj_t * ui_BookName3;
extern lv_obj_t * ui_PageNum3;
extern lv_obj_t * ui_LastOpen3;
extern lv_obj_t * ui_BatLogoWhite;
extern lv_obj_t * ui_BookSelPercentage;
extern lv_obj_t * ui_BookSelect;
extern lv_obj_t * ui_BookSelTime;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

