// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: mykindlereader

#include "ui.h"

lv_obj_t * ui_BookSelection = NULL;
lv_obj_t * ui_BookChoicePanel = NULL;
lv_obj_t * ui_TopBarPanel = NULL;
lv_obj_t * ui_Divider = NULL;
lv_obj_t * ui_Divider1 = NULL;
lv_obj_t * ui_Divider2 = NULL;
lv_obj_t * ui_BookName = NULL;
lv_obj_t * ui_PageNum = NULL;
lv_obj_t * ui_LastOpen = NULL;
lv_obj_t * ui_BookName1 = NULL;
lv_obj_t * ui_PageNum1 = NULL;
lv_obj_t * ui_LastOpen1 = NULL;
lv_obj_t * ui_BookName2 = NULL;
lv_obj_t * ui_PageNum2 = NULL;
lv_obj_t * ui_LastOpen2 = NULL;
lv_obj_t * ui_BookName3 = NULL;
lv_obj_t * ui_PageNum3 = NULL;
lv_obj_t * ui_LastOpen3 = NULL;
lv_obj_t * ui_BatLogoWhite = NULL;
lv_obj_t * ui_BookSelPercentage = NULL;
lv_obj_t * ui_BookSelect = NULL;
lv_obj_t * ui_BookSelTime = NULL;
// event funtions

// build funtions

void ui_BookSelection_screen_init(void)
{
    ui_BookSelection = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BookSelection, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_BookSelection, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BookChoicePanel = lv_obj_create(ui_BookSelection);
    lv_obj_set_width(ui_BookChoicePanel, 286);
    lv_obj_set_height(ui_BookChoicePanel, 103);
    lv_obj_set_x(ui_BookChoicePanel, 0);
    lv_obj_set_y(ui_BookChoicePanel, 9);
    lv_obj_set_align(ui_BookChoicePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BookChoicePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BookChoicePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BookChoicePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopBarPanel = lv_obj_create(ui_BookSelection);
    lv_obj_set_width(ui_TopBarPanel, 291);
    lv_obj_set_height(ui_TopBarPanel, 19);
    lv_obj_set_x(ui_TopBarPanel, 0);
    lv_obj_set_y(ui_TopBarPanel, -54);
    lv_obj_set_align(ui_TopBarPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopBarPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopBarPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBarPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopBarPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopBarPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider = lv_obj_create(ui_BookSelection);
    lv_obj_set_width(ui_Divider, 291);
    lv_obj_set_height(ui_Divider, 6);
    lv_obj_set_x(ui_Divider, -2);
    lv_obj_set_y(ui_Divider, -18);
    lv_obj_set_align(ui_Divider, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Divider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Divider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider1 = lv_obj_create(ui_BookSelection);
    lv_obj_set_width(ui_Divider1, 291);
    lv_obj_set_height(ui_Divider1, 6);
    lv_obj_set_x(ui_Divider1, -1);
    lv_obj_set_y(ui_Divider1, 6);
    lv_obj_set_align(ui_Divider1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Divider1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Divider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider2 = lv_obj_create(ui_BookSelection);
    lv_obj_set_width(ui_Divider2, 291);
    lv_obj_set_height(ui_Divider2, 6);
    lv_obj_set_x(ui_Divider2, 0);
    lv_obj_set_y(ui_Divider2, 33);
    lv_obj_set_align(ui_Divider2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Divider2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Divider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BookName = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_BookName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BookName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BookName, -108);
    lv_obj_set_y(ui_BookName, -30);
    lv_obj_set_align(ui_BookName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BookName, "BookName");
    lv_obj_set_style_text_font(ui_BookName, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PageNum = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_PageNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PageNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PageNum, -2);
    lv_obj_set_y(ui_PageNum, -30);
    lv_obj_set_align(ui_PageNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PageNum, "PageNum");
    lv_obj_set_style_text_font(ui_PageNum, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LastOpen = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_LastOpen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LastOpen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LastOpen, 107);
    lv_obj_set_y(ui_LastOpen, -30);
    lv_obj_set_align(ui_LastOpen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LastOpen, "LastOpen");
    lv_obj_set_style_text_font(ui_LastOpen, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BookName1 = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_BookName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BookName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BookName1, -108);
    lv_obj_set_y(ui_BookName1, -7);
    lv_obj_set_align(ui_BookName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BookName1, "BookName");
    lv_obj_set_style_text_font(ui_BookName1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PageNum1 = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_PageNum1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PageNum1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PageNum1, -2);
    lv_obj_set_y(ui_PageNum1, -7);
    lv_obj_set_align(ui_PageNum1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PageNum1, "PageNum");
    lv_obj_set_style_text_font(ui_PageNum1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LastOpen1 = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_LastOpen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LastOpen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LastOpen1, 107);
    lv_obj_set_y(ui_LastOpen1, -6);
    lv_obj_set_align(ui_LastOpen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LastOpen1, "LastOpen");
    lv_obj_set_style_text_font(ui_LastOpen1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BookName2 = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_BookName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BookName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BookName2, -108);
    lv_obj_set_y(ui_BookName2, 19);
    lv_obj_set_align(ui_BookName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BookName2, "BookName");
    lv_obj_set_style_text_font(ui_BookName2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PageNum2 = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_PageNum2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PageNum2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PageNum2, -2);
    lv_obj_set_y(ui_PageNum2, 18);
    lv_obj_set_align(ui_PageNum2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PageNum2, "PageNum");
    lv_obj_set_style_text_font(ui_PageNum2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LastOpen2 = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_LastOpen2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LastOpen2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LastOpen2, 107);
    lv_obj_set_y(ui_LastOpen2, 18);
    lv_obj_set_align(ui_LastOpen2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LastOpen2, "LastOpen");
    lv_obj_set_style_text_font(ui_LastOpen2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BookName3 = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_BookName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BookName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BookName3, -108);
    lv_obj_set_y(ui_BookName3, 45);
    lv_obj_set_align(ui_BookName3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BookName3, "BookName");
    lv_obj_set_style_text_font(ui_BookName3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PageNum3 = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_PageNum3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PageNum3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PageNum3, -2);
    lv_obj_set_y(ui_PageNum3, 45);
    lv_obj_set_align(ui_PageNum3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PageNum3, "PageNum");
    lv_obj_set_style_text_font(ui_PageNum3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LastOpen3 = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_LastOpen3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LastOpen3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LastOpen3, 107);
    lv_obj_set_y(ui_LastOpen3, 45);
    lv_obj_set_align(ui_LastOpen3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LastOpen3, "LastOpen");
    lv_obj_set_style_text_font(ui_LastOpen3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatLogoWhite = lv_img_create(ui_BookSelection);
    lv_img_set_src(ui_BatLogoWhite, &ui_img_battery_android_frame_full_20dp_ffffff_fill0_wght400_grad0_opsz20_png);
    lv_obj_set_width(ui_BatLogoWhite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatLogoWhite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatLogoWhite, 91);
    lv_obj_set_y(ui_BatLogoWhite, -54);
    lv_obj_set_align(ui_BatLogoWhite, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatLogoWhite, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BatLogoWhite, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BookSelPercentage = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_BookSelPercentage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BookSelPercentage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BookSelPercentage, 122);
    lv_obj_set_y(ui_BookSelPercentage, -54);
    lv_obj_set_align(ui_BookSelPercentage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BookSelPercentage, "100%");
    lv_obj_set_style_text_color(ui_BookSelPercentage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BookSelPercentage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BookSelect = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_BookSelect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BookSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BookSelect, -106);
    lv_obj_set_y(ui_BookSelect, -54);
    lv_obj_set_align(ui_BookSelect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BookSelect, "Select your book");
    lv_obj_set_style_text_color(ui_BookSelect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BookSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BookSelect, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BookSelTime = lv_label_create(ui_BookSelection);
    lv_obj_set_width(ui_BookSelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BookSelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BookSelTime, 3);
    lv_obj_set_y(ui_BookSelTime, -53);
    lv_obj_set_align(ui_BookSelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BookSelTime, "11:47");
    lv_obj_set_style_text_color(ui_BookSelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BookSelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BookSelTime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_BookSelection_screen_destroy(void)
{
    if(ui_BookSelection) lv_obj_del(ui_BookSelection);

    // NULL screen variables
    ui_BookSelection = NULL;
    ui_BookChoicePanel = NULL;
    ui_TopBarPanel = NULL;
    ui_Divider = NULL;
    ui_Divider1 = NULL;
    ui_Divider2 = NULL;
    ui_BookName = NULL;
    ui_PageNum = NULL;
    ui_LastOpen = NULL;
    ui_BookName1 = NULL;
    ui_PageNum1 = NULL;
    ui_LastOpen1 = NULL;
    ui_BookName2 = NULL;
    ui_PageNum2 = NULL;
    ui_LastOpen2 = NULL;
    ui_BookName3 = NULL;
    ui_PageNum3 = NULL;
    ui_LastOpen3 = NULL;
    ui_BatLogoWhite = NULL;
    ui_BookSelPercentage = NULL;
    ui_BookSelect = NULL;
    ui_BookSelTime = NULL;

}
