// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: mykindlereader

#include "ui.h"

lv_obj_t * ui_MainMenu = NULL;
lv_obj_t * ui_tree = NULL;
lv_obj_t * ui_cat = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_batterypercentage = NULL;
lv_obj_t * ui_batlogoblack = NULL;
// event funtions

// build funtions

void ui_MainMenu_screen_init(void)
{
    ui_MainMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_MainMenu, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tree = lv_img_create(ui_MainMenu);
    lv_img_set_src(ui_tree, &ui_img_output_png);
    lv_obj_set_width(ui_tree, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tree, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tree, -82);
    lv_obj_set_y(ui_tree, 10);
    lv_obj_set_align(ui_tree, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tree, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tree, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cat = lv_img_create(ui_MainMenu);
    lv_img_set_src(ui_cat, &ui_img_car_png);
    lv_obj_set_width(ui_cat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cat, 30);
    lv_obj_set_y(ui_cat, 35);
    lv_obj_set_align(ui_cat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cat, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_MainMenu);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 94);
    lv_obj_set_y(ui_time, -32);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "11:47");
    lv_obj_set_style_text_font(ui_time, &ui_font_clockFont1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_MainMenu);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 96);
    lv_obj_set_y(ui_date, -6);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "19th March");

    ui_batterypercentage = lv_label_create(ui_MainMenu);
    lv_obj_set_width(ui_batterypercentage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batterypercentage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batterypercentage, 119);
    lv_obj_set_y(ui_batterypercentage, 47);
    lv_obj_set_align(ui_batterypercentage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batterypercentage, "100%");
    lv_obj_set_style_text_font(ui_batterypercentage, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batlogoblack = lv_img_create(ui_MainMenu);
    lv_img_set_src(ui_batlogoblack, &ui_img_battery_android_frame_full_20dp_000000_fill0_wght400_grad0_opsz20_png);
    lv_obj_set_width(ui_batlogoblack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batlogoblack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batlogoblack, 90);
    lv_obj_set_y(ui_batlogoblack, 48);
    lv_obj_set_align(ui_batlogoblack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batlogoblack, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batlogoblack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_MainMenu_screen_destroy(void)
{
    if(ui_MainMenu) lv_obj_del(ui_MainMenu);

    // NULL screen variables
    ui_MainMenu = NULL;
    ui_tree = NULL;
    ui_cat = NULL;
    ui_time = NULL;
    ui_date = NULL;
    ui_batterypercentage = NULL;
    ui_batlogoblack = NULL;

}
