// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: mykindlereader

#ifndef UI_READINGSCREEN_H
#define UI_READINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ReadingScreen
extern void ui_ReadingScreen_screen_init(void);
extern void ui_ReadingScreen_screen_destroy(void);
extern lv_obj_t * ui_ReadingScreen;
extern lv_obj_t * ui_TopBarReading;
extern lv_obj_t * ui_TimeReading;
extern lv_obj_t * ui_PageNumRead;
extern lv_obj_t * ui_heart;
extern lv_obj_t * ui_TextZone;
extern lv_obj_t * ui_BookIcon;
extern lv_obj_t * ui_ClockIcon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

