// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: mykindlereader

#include "ui.h"

lv_obj_t * ui_ReadingScreen = NULL;
lv_obj_t * ui_TopBarReading = NULL;
lv_obj_t * ui_TimeReading = NULL;
lv_obj_t * ui_PageNumRead = NULL;
lv_obj_t * ui_heart = NULL;
lv_obj_t * ui_TextZone = NULL;
lv_obj_t * ui_BookIcon = NULL;
lv_obj_t * ui_ClockIcon = NULL;
// event funtions

// build funtions

void ui_ReadingScreen_screen_init(void)
{
    ui_ReadingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ReadingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBarReading = lv_obj_create(ui_ReadingScreen);
    lv_obj_set_width(ui_TopBarReading, 300);
    lv_obj_set_height(ui_TopBarReading, 18);
    lv_obj_set_x(ui_TopBarReading, 0);
    lv_obj_set_y(ui_TopBarReading, -56);
    lv_obj_set_align(ui_TopBarReading, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopBarReading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopBarReading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBarReading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeReading = lv_label_create(ui_ReadingScreen);
    lv_obj_set_width(ui_TimeReading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeReading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeReading, -103);
    lv_obj_set_y(ui_TimeReading, -56);
    lv_obj_set_align(ui_TimeReading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeReading, "11:47");
    lv_obj_set_style_text_color(ui_TimeReading, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeReading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeReading, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PageNumRead = lv_label_create(ui_ReadingScreen);
    lv_obj_set_width(ui_PageNumRead, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PageNumRead, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PageNumRead, 106);
    lv_obj_set_y(ui_PageNumRead, -57);
    lv_obj_set_align(ui_PageNumRead, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PageNumRead, "Page 1");
    lv_obj_set_style_text_color(ui_PageNumRead, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PageNumRead, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PageNumRead, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heart = lv_img_create(ui_ReadingScreen);
    lv_img_set_src(ui_heart, &ui_img_heart_smile_20dp_ea3323_fill0_wght400_grad0_opsz20_png);
    lv_obj_set_width(ui_heart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heart, 1);
    lv_obj_set_y(ui_heart, -56);
    lv_obj_set_align(ui_heart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heart, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_heart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextZone = lv_obj_create(ui_ReadingScreen);
    lv_obj_remove_style_all(ui_TextZone);
    lv_obj_set_width(ui_TextZone, 287);
    lv_obj_set_height(ui_TextZone, 103);
    lv_obj_set_x(ui_TextZone, 0);
    lv_obj_set_y(ui_TextZone, 7);
    lv_obj_set_align(ui_TextZone, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TextZone, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BookIcon = lv_img_create(ui_ReadingScreen);
    lv_img_set_src(ui_BookIcon, &ui_img_book_17dp_ffffff_fill0_wght400_grad0_opsz20_png);
    lv_obj_set_width(ui_BookIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BookIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BookIcon, 78);
    lv_obj_set_y(ui_BookIcon, -56);
    lv_obj_set_align(ui_BookIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BookIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BookIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockIcon = lv_img_create(ui_ReadingScreen);
    lv_img_set_src(ui_ClockIcon, &ui_img_nest_clock_farsight_analog_17dp_ffffff_fill0_wght400_grad0_opsz20_png);
    lv_obj_set_width(ui_ClockIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockIcon, -125);
    lv_obj_set_y(ui_ClockIcon, -56);
    lv_obj_set_align(ui_ClockIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClockIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ClockIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_ReadingScreen_screen_destroy(void)
{
    if(ui_ReadingScreen) lv_obj_del(ui_ReadingScreen);

    // NULL screen variables
    ui_ReadingScreen = NULL;
    ui_TopBarReading = NULL;
    ui_TimeReading = NULL;
    ui_PageNumRead = NULL;
    ui_heart = NULL;
    ui_TextZone = NULL;
    ui_BookIcon = NULL;
    ui_ClockIcon = NULL;

}
